echo "=========================================data-finisher=========================================="
while true
do
 pkg update -y
pkg upgrade -y
pkg uninstall ubuntu-rootfs -y
pkg uninstall debian-rootfs -y
pkg uninstall archlinux-rootfs -y
pkg uninstall git-annex -y
pkg uninstall rtorrent -y
pkg uninstall transmission -y
pkg uninstall emacs -y
pkg uninstall vim -y
pkg uninstall python -y
pkg uninstall java -y
pkg uninstall nodejs -y
pkg uninstall ruby -y
pkg uninstall gcc -y
pkg uninstall clang -y
pkg uninstall ffmpeg -y
pkg uninstall wget -y
pkg uninstall bash -y
pkg uninstall zsh -y
pkg uninstall nano -y
pkg uninstall curl -y
pkg uninstall ssh -y
pkg uninstall nethogs -y
pkg uninstall iftop -y
pkg uninstall termux-api -y
pkg install ubuntu-rootfs -y
pkg install debian-rootfs -y
pkg install archlinux-rootfs -y
pkg install git-annex -y
pkg install rtorrent -y
pkg install transmission -y
pkg install emacs -y
pkg install vim -y
pkg install python -y
pkg install java -y
pkg install nodejs -y
pkg install ruby -y
pkg install gcc -y
pkg install clang -y
pkg install ffmpeg -y
pkg install wget -y
pkg install bash -y
pkg install zsh -y
pkg install nano -y
pkg install curl -y
pkg install ssh -y
pkg install nethogs -y
pkg install iftop -y
pkg install termux-api -y
pkg uninstall ubuntu-rootfs -y
pkg uninstall debian-rootfs -y
pkg uninstall archlinux-rootfs -y
pkg uninstall git-annex -y
pkg uninstall rtorrent -y
pkg uninstall transmission -y
pkg uninstall emacs -y
pkg uninstall vim -y
pkg uninstall python -y
pkg uninstall java -y
pkg uninstall nodejs -y
pkg uninstall ruby -y
pkg uninstall gcc -y
pkg uninstall clang -y
pkg uninstall ffmpeg -y
pkg uninstall wget -y
pkg uninstall bash -y
pkg uninstall zsh -y
pkg uninstall nano -y
pkg uninstall curl -y
pkg uninstall ssh -y
pkg uninstall nethogs -y
pkg uninstall iftop -y
pkg uninstall termux-api -y
done
